const { PROJECT_STATUS, TASK_STATUS, MILESTONE_STATUS, PAYMENT_STATUS, INVOICE_STATUS, PRIORITY } = require('./status');
const { USER_ROLES, PROJECT_ROLES, PERMISSIONS, PROJECT_PERMISSIONS } = require('./roles');

module.exports = {
  // Status constants
  PROJECT_STATUS,
  TASK_STATUS,
  MILESTONE_STATUS,
  PAYMENT_STATUS,
  INVOICE_STATUS,
  PRIORITY,
  
  // Role constants
  USER_ROLES,
  PROJECT_ROLES,
  PERMISSIONS,
  PROJECT_PERMISSIONS
};

